// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyQuanCaPhe.Data;

#nullable disable

namespace QuanLyQuanCaPhe.Migrations
{
    [DbContext(typeof(CaPheDbContext))]
    [Migration("20260327083029_ChuanHoaTaiKhoanVaVaiTro")]
    partial class ChuanHoaTaiKhoanVaVaiTro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtHoaDon_ChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DonGiaBan")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("MonID")
                        .HasColumnType("int");

                    b.Property<short>("SoLuongBan")
                        .HasColumnType("smallint");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("MonID");

                    b.ToTable("HoaDon_ChiTiet");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaBan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Ban");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaHoadon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BanID")
                        .HasColumnType("int");

                    b.Property<string>("GhiChuHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BanID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaKhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaLoaiMon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LoaiMon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaMon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiMonID")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LoaiMonID");

                    b.ToTable("Mon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaNhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("HoatDong")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VaiTroID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.HasIndex("VaiTroID");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaVaiTro", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtHoaDon_ChiTiet", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.dtaHoadon", "HoaDon")
                        .WithMany("HoaDon_ChiTiet")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.dtaMon", "Mon")
                        .WithMany("HoaDon_ChiTiet")
                        .HasForeignKey("MonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Mon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaHoadon", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.dtaBan", "Ban")
                        .WithMany("HoaDon")
                        .HasForeignKey("BanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.dtaKhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.dtaNhanVien", "NhanVien")
                        .WithMany("HoaDon")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaMon", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.dtaLoaiMon", "LoaiMon")
                        .WithMany("Mon")
                        .HasForeignKey("LoaiMonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiMon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaUser", b =>
                {
                    b.HasOne("QuanLyQuanCaPhe.Data.dtaNhanVien", "NhanVien")
                        .WithOne("User")
                        .HasForeignKey("QuanLyQuanCaPhe.Data.dtaUser", "NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyQuanCaPhe.Data.dtaVaiTro", "VaiTro")
                        .WithMany("Users")
                        .HasForeignKey("VaiTroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaBan", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaHoadon", b =>
                {
                    b.Navigation("HoaDon_ChiTiet");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaKhachHang", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaLoaiMon", b =>
                {
                    b.Navigation("Mon");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaMon", b =>
                {
                    b.Navigation("HoaDon_ChiTiet");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaNhanVien", b =>
                {
                    b.Navigation("HoaDon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyQuanCaPhe.Data.dtaVaiTro", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
